name: CI - Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the database
      run: |
        export DATABASE_URI="sqlite:///test.db"
        flask db upgrade
        flask db create
        flask db seed

    - name: Run tests
      run: |
        PYTHONPATH=. pytest --junitxml=test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: test-results.xml
