name: CI - Run Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FLASK_APP: app.py
      FLASK_ENV: testing
      DATABASE_URI: sqlite:///test.db

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up the test database
      run: |
        flask db create
        flask db seed

    - name: Run tests
      run: |
        PYTHONPATH=. pytest --junitxml=test-results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: test-results.xml