name: Build Flask Docker App with Secrets

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      FLASK_ENV: ${{ secrets.FLASK_ENV }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with secrets
        run: |
          docker build \
            --build-arg DATABASE_URI="$DATABASE_URI" \
            --build-arg FLASK_ENV="$FLASK_ENV" \
            --build-arg SECRET_KEY="$SECRET_KEY" \
            -t workplace_db:ci .

      - name: Run container (basic test)
        run: |
          docker run --rm \
            -e DATABASE_URI="$DATABASE_URI" \
            -e FLASK_ENV="$FLASK_ENV" \
            -e SECRET_KEY="$SECRET_KEY" \
            workplace_db:ci python --version
